Repository FiveI-s/IDo, pull requests merged in 2023-10, with the labels that each got.

#2 [feat] Color, Font 기본 셋팅
  .github/ISSUE_TEMPLATE/기능 요청.md
  .github/ISSUE_TEMPLATE/버그템플릿.md
  .github/pull_request_template.md
  IDo.xcodeproj/project.pbxproj
  IDo/Assets.xcassets/Colors/Contents.json
  IDo/Assets.xcassets/Colors/background/Background.colorset/Contents.json
  IDo/Assets.xcassets/Colors/background/BackgroundSecondary.colorset/Contents.json
  IDo/Assets.xcassets/Colors/background/BackgroundTertiary.colorset/Contents.json
  IDo/Assets.xcassets/Colors/background/Contents.json
  IDo/Assets.xcassets/Colors/border/BorderOpaque.colorset/Contents.json
  IDo/Assets.xcassets/Colors/border/BorderSelected.colorset/Contents.json
  IDo/Assets.xcassets/Colors/border/Contents.json
  IDo/Assets.xcassets/Colors/content/ContentPrimary-Press.colorset/Contents.json
  IDo/Assets.xcassets/Colors/content/ContentPrimay.colorset/Contents.json
  IDo/Assets.xcassets/Colors/content/Contents.json
  IDo/Assets.xcassets/Colors/core/Contents.json
  IDo/Assets.xcassets/Colors/core/Negative.colorset/Contents.json
  IDo/Assets.xcassets/Colors/core/Primary.colorset/Contents.json
  IDo/Assets.xcassets/Colors/core/Secondary.colorset/Contents.json
  IDo/Assets.xcassets/Colors/text/Contents.json
  IDo/Assets.xcassets/Colors/text/Placeholder.colorset/Contents.json
  IDo/Assets.xcassets/Colors/text/Text1.colorset/Contents.json
  IDo/Assets.xcassets/Colors/text/Text2.colorset/Contents.json
  IDo/Assets.xcassets/Colors/text/TextReadOnly.colorset/Contents.json
  IDo/Assets.xcassets/Colors/text/TextStrong.colorset/Contents.json
  IDo/Util/Color.swift
  IDo/Util/Font.swift
Labels: enhancement

#3 [FEAT] TabBar 추가 & VC 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Assets.xcassets/Colors/core/Main.colorset/Contents.json
  IDo/Assets.xcassets/Colors/core/Sub.colorset/Contents.json
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticePage/NoticeViewController.swift
  IDo/Page/TabBarController.swift
  IDo/Util/Color.swift
  IDo/Util/Margin.swift
Labels: Feature

#4 [FIX] TabBar 버튼 추가
  IDo/Page/TabBarController.swift
  IDo/SceneDelegate.swift
Labels: UI

#12 BasicImageView, EmptyMessageStackView 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Assets.xcassets/Colors/core/Black.colorset/Contents.json
  IDo/Assets.xcassets/Colors/core/White.colorset/Contents.json
  IDo/Util/Color.swift
  IDo/View/BasicImageView.swift
  IDo/View/EmptyMessageStackView.swift
Labels: Feature

#15 Feature/notice board page
  IDo.xcodeproj/project.pbxproj
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardView.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/TabBarController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#17 [RENAME] : ✏️ Basic Cell 파일 옮기기
  IDo.xcodeproj/project.pbxproj
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/GalleryCollectionViewCell.swift
Labels: Doc

#25 [FEAT]: 데이터 모델 구조 구현
  IDo.xcodeproj/project.pbxproj
  IDo/IDo.xcdatamodeld/.xccurrentversion
  IDo/IDo.xcdatamodeld/IDo.xcdatamodel/contents
  IDo/Model/Category.swift
  IDo/Model/Club.swift
  IDo/Model/Comment.swift
  IDo/Model/NoticeBoard.swift
  IDo/Model/User.swift
Labels: Feature

#32 [PACK] : 🎁 파이어베이스 패키지 기본 셋팅
  IDo.xcodeproj/project.pbxproj
  IDo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IDo/AppDelegate.swift
  IDo/GoogleService-Info.plist
  IDo/SceneDelegate.swift
Labels: Feature

#39 [FEAT] : ⚙️ 게시판 디테일 화면 파이어베이스 연결작업
  IDo.xcodeproj/project.pbxproj
  IDo/Enum/ViewState.swift
  IDo/Extenstion/Date.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/Cell/EmptyCountTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/CommentUpdateViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseDataManager/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/CommentStackView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/View/EmptyMessageStackView.swift
Labels: Feature, UI

#50 ⚙️ 카카오톡으로 로그인 한 사용자의 정보로 댓글을 달도록 구현 + SceneDelegate 에서 토큰이 존재하면 구글 로그인이 되도록 수정
  IDo.xcodeproj/project.pbxproj
  IDo/Extenstion/Encodable.swift
  IDo/Model/Category.swift
  IDo/Model/Club.swift
  IDo/Model/Comment.swift
  IDo/Model/NoticeBoard.swift
  IDo/Model/User.swift
  IDo/Model/UserSummary.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/CommentUpdateViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseDataManager/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/SceneDelegate.swift
Labels: Feature

#52 [feat] 파이어베이스 DB CRUD 기능을 하는 FBDataManager 클래스 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Model/Category.swift
  IDo/Model/Club.swift
  IDo/Model/Comment.swift
  IDo/Model/FBDataManager.swift
  IDo/Model/User.swift
  IDo/Model/UserSummary.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Util/Identifier.swift
Labels: Feature

#54 [feat] 회원가입시 user의 정보가 db에 저장됨
  IDo.xcodeproj/project.pbxproj
  IDo/Model/Club.swift
  IDo/Model/IDoUser.swift
  IDo/Model/NoticeBoard.swift
  IDo/Page/LoginPage/LoginViewController.swift
Labels: Feature

#55 [FEAT] : ⚙️ 내 댓글만 삭제 수정 가능하도록 기능 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/CommentUpdateViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
Labels: Feature

#58 [FEAT] : ⚙️ 가입시 DB User에 myClubList에 저장 + 가입되어있는 경우 가입하기 버튼 숨기기 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Extenstion/Encodable.swift
  IDo/Model/Club.swift
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature, UI

#61 [FEAT] 마이프로필 수정 버튼 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/HomePage/HomeViewcell.swift
  IDo/Page/MyProfilePage/MyProfileViewCell.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: Feature

#62 [feature] 파이어베이스 회원가입 로그인 뼈대 UI 및 기능 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Extenstion/Encodable.swift
  IDo/Model/FBDatabaseManager.swift
  IDo/Model/IDoUser.swift
  IDo/Model/UserSummary.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/Cell/CategoryCollectionViewCell.swift
  IDo/Page/SignUpPage/LoginInfo.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature, UI

#63 [FEAT]: 로그인 알림 및 비밀번호 숨기기 6자 이상 확인 기능 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#64 [FEAT] : ⚙️ clubID 가져오기
  IDo.xcodeproj/project.pbxproj
  IDo.xcodeproj/xcuserdata/hong-junyoung.xcuserdatad/xcschemes/xcschememanagement.plist
  IDo/Model/NoticeBoard.swift
  IDo/Page/CategoryPage/Cell/CategoryCell.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/GalleryCollectionViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardCell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#67 [MERGE]: Feature/notice page -> develop
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/Cell/CategoryCollectionViewCell.swift
  IDo/SceneDelegate.swift
Labels: Feature

#69 [FEAT] : ⚙ NoticeBoard Comment 연결 작업
  IDo/Model/NoticeBoard.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#70 [FEAT] : ⚙ 댓글창 프로필 이미지, 닉네임이 출력되도록 기능 구현
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/CommentStackView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
Labels: Feature, UI

#72 [MERGE]: feature/notice-page -> develop
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#73 [FEAT] #71 meeting 수정시 추가 생성되는 것 개선, 생성시 autoid로 고유 키 값 설정
  IDo/Model/TemporaryManager.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
Labels: Feature

#75 [FEAT] 게시판이 없을 때 알림 창 & 댓글 개수 연결
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#74 [FEAT] : ⚙ 사용자 프로필 이미지 불러오는 속도 개선
  IDo.xcodeproj/project.pbxproj
  IDo/Enum/UserImageSize.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Util/URLCache.swift
Labels: Feature

#76 [FEAT] : ⚙️ 게시판에 댓글 갯수가 출력되도록 기능 구현
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#77 [fix] URLCache 싱글톤으로 수정
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/SceneDelegate.swift
  IDo/Util/URLCache.swift
Labels: Feature

#80 [FEAT]: 모임 미가입시 게시판 숨김 기능 구현
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#81 [FEAT] : ⚙ 댓글을 달면 모든 댓글을 다시 그리지 않도록 수정 + FBURLCache에서 Data가 아니라 UIImage를 반환하도록 변경
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Util/FBURLCache.swift
Labels: BUG, Feature

#82 [FIX] : 🔧 UserSummary description 프로퍼티 제거, UIImage extenstion으로 ImageResize 메서드 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Enum/ImageSize.swift
  IDo/Extenstion/UIImage.swift
  IDo/Model/UserSummary.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/FirebaseCreateUserManager.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
Labels: Refactor, Feature

#85 [FEAT]: 버그 해결
  IDo.xcodeproj/project.pbxproj
  IDo/Model/MeetingsData.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
Labels: BUG

#86 [FEAT] : ⚙️ 로그인한 유저 정보를 가지고 있는 클래스(Util/MyProfile) 싱글톤 패턴으로 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Model/IDoUser.swift
  IDo/Model/MyUserInfo.swift
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/FirebaseCreateUserManager.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/TabBarController.swift
  IDo/Util/MyProfile.swift
  IDo/Util/ProfileImageCache.swift
Labels: Feature

#88 [FEAT] : ⚙️ 이미지가 업데이트 된경우 캐싱되어있는 내용이 업데이트 되도록 기능 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Extenstion/Data.swift
  IDo/Model/MeetingsData.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/SignUpPage/FirebaseCreateUserManager.swift
  IDo/SceneDelegate.swift
  IDo/Util/FBURLCache.swift
  IDo/Util/MyProfile.swift
Labels: Feature

#89 [FEAT] 이미지 수정 시, 중복 저장 1차 해결
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardImagePicker.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/GalleryCollectionViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
Labels: Feature

#90 [FIX] : 🐛 이미지 캐싱 코드의 변경에 따른 코드 변경(download함수 수정)
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
Labels: Feature

#92 [FEAT]: 가입하기 클릭시 게시판 즉각 확인 구현
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#93 [FEAT] 게시판 디테일 화면에서 더보기 버튼 클릭시 알림창 뜨고 수정버튼 클릭시 수정화면으로 넘어가도록 구현(삭제 기능 미구현)
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/SceneDelegate.swift
  IDo/View/AlertManager.swift
Labels: UI

#97 [FIX]: 회원가입 시 카테고리 최대 3개로 제한
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature

#99 [[FEAT] : ⚙ 게시판 디테일 화면에 이미지가 들어가도록 구현
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/SceneDelegate.swift
Labels: UI

#100 [fix] 게시판 생성후 바로 생성한 게시판을 들어가면 튕기는 버그
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
Labels: UI

#101 Feature/notice board page
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardCell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#104 [FEAT]: 이메일 인증 구현 및 여러경우 알람창 띄움
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature

#107 [FEAT]: 회원가입 화면 구현, 로그인 회원가입 첫 입력시 대문자 입력 버그 수정
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, Feature, UI

#108 [DESIGN] : 🎨 로그인 UI 변경, 폰트 변경
  IDo/Assets.xcassets/Login/logo.imageset/Contents.json
  IDo/Assets.xcassets/Login/logo.imageset/Group 146.png
  IDo/Assets.xcassets/Login/logo.imageset/Group 146_2.png
  IDo/Assets.xcassets/Login/logo.imageset/Group 146_3.png
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/MyProfilePage/MyProfileViewCell.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCell/NoticeBoardTableViewCell.swift
  IDo/Util/Font.swift
Labels: UI

#109 [FEAT] 사용자가 생성한 게시판, 댓글 DB에 저장
  IDo/Model/FBDatabaseManager.swift
  IDo/Model/NoticeBoard.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/CommentStackView.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/SceneDelegate.swift
  IDo/Util/FBURLCache.swift
  IDo/Util/MyProfile.swift
Labels: Feature

#113 [FEAT] 가입 버튼 클릭시 Club UserList에 추가되도록 기능 구현
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Util/MyProfile.swift
  IDo/View/EmptyMessageStackView.swift
Labels: Feature
