Repository FiveI-s/IDo, pull requests merged in 2023-11, with the labels that each got.

#116 [FEAT] 파이어베이스 db에서 가져오는 부분을 전부 decoding을 사용하도록 변경, IdoUser의 profileImage을 profileImagePath로 변경
  IDo/Model/Club.swift
  IDo/Model/IDoUser.swift
  IDo/Model/MeetingsData.swift
  IDo/Model/MyUserInfo.swift
  IDo/Model/NoticeBoard.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/FirebaseCreateUserManager.swift
  IDo/Util/MyProfile.swift
Labels: Refactor

#118 [BUG] Club에 UserList를 저장하지 못하는 버그 수정
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Util/MyProfile.swift
  IDo/View/EmptyMessageStackView.swift
Labels: BUG

#120 [FEAT] Club 유저리스트 추가 기능
  IDo/Model/Club.swift
  IDo/Model/IDoUser.swift
  IDo/Model/MeetingsData.swift
  IDo/Model/MyUserInfo.swift
  IDo/Model/NoticeBoard.swift
  IDo/Model/UserSummary.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/FirebaseCreateUserManager.swift
  IDo/Util/MyProfile.swift
Labels: Refactor

#121 [FEAT]: 회원가입 페이지 UI 구성 및 기능변경
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature, UI

#122 [DESIGN]: 회원가입페이지 UI 변경
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: UI

#123 [FEAT] 게시판 삭제시 관련 댓글도 삭제되도록 구현
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/CommentUpdateViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#125 [FEAT]: 회원가입시 프로필화면 버튼 키보드에 반응하여 움직이도록 구현
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, Feature

#126 [DESIGN] : 🎨 basic cell 수정 및 네비게이션 뒤로가기 텍스트 수정
  IDo/Assets.xcassets/Colors/content/ContentDisable.colorset/Contents.json
  IDo/Base.lproj/LaunchScreen.storyboard
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/TabBarController.swift
  IDo/Util/Color.swift
  IDo/View/BasicCell.swift
Labels: Refactor

#127 [FIX]: 로그인페이지 화면 클릭시 키보드 내림 구현, 인증버튼만 클릭 시 중복확인 버튼 클릭 알람창 구현
  IDo.xcodeproj/project.pbxproj
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, Refactor

#128 [FEAT]: 회원가입 시 프로필화면 자기소개 추가
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/SceneDelegate.swift
Labels: Feature, UI

#129 [REFACTOR] : ♻️ 홈 화면 cell 변경 HomeViewCell -> BasicCell
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/NoticeBoardEmptyView.swift
  IDo/Page/NoticeBoard/NoticeBoardView.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/View/BasicCell.swift
Labels: UI

#130 [FIX]: 카테고리 페이지 레이아웃 수정, 회원가입 카테고리 선택 화면 수정
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/CategoryPage/Cell/CategoryCollectionCell.swift
  IDo/Page/LoginPage/LoginView.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/Cell/CategoryCollectionViewCell.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Refactor, UI

#131 [FEAT] 모임 삭제 기능 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Extenstion/Encodable.swift
  IDo/Model/Club.swift
  IDo/Model/MeetingsData.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/FirebaseUserDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Util/MyProfile.swift
Labels: Feature

#132 [FIX]: 카테고리 디자인 변경 및 체크박스 버튼 구현
  IDo/Page/CategoryPage/Cell/CategoryCollectionCell.swift
  IDo/Page/SignUpPage/Cell/CategoryCollectionViewCell.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature, UI

#133 [FEAT] : ⚙️ 게시글 작성 유저가 아니면 신고하기 창 띄우기
  IDo/Model/IDoUser.swift
  IDo/Model/UserSummary.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/SceneDelegate.swift
  IDo/View/AlertManager.swift
Labels: Feature

#137 [FEAT] : ⚙️ 신고하기 기능 -> NoticeBoard 삭제 완료 & 방출 기능 진행 중
  IDo/Model/NoticeBoard.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#138 [FEAT]: 로그아웃, 회원탈퇴 기능 구현,로그인 버튼,회원가입 버튼 UI 변경
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature, UI

#139 [FIX]: 회원탈퇴 재수정
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: Feature

#140 [FEAT] : ⚙️ 신고하기 기능 -> 방출 기능 구현 완료
  IDo/Model/MyUserInfo.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#141 [DESIGN]: Basic Cell 및 Profilepage 오토레이아웃 오류 해결
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/View/BasicCell.swift
Labels: BUG

#142 [FEAT] 맴버 목록 보이도록 UI 추가, 맴버 추방 기능
  IDo.xcodeproj/project.pbxproj
  IDo/Model/IDoUser.swift
  IDo/Model/MyUserInfo.swift
  IDo/Model/UserSummary.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoard/View/IntrinsicTableView.swift
  IDo/Page/NoticeBoard/View/MemberListHeaderView.swift
Labels: Feature, UI

#145 [FEAT]: 카테고리 닉네임 페이지 미입력시 로그인페이지에서 뜨게 구현
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature

#147 [FEAT] 댓글 신고 기능 추가
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#149 [FEAT] 홈 화면 모임 이미지 다운로드
  IDo.xcodeproj/project.pbxproj
  IDo/Model/IDoUser.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/HomeEmptyView.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/TabBarController.swift
  IDo/Util/MyProfile.swift
Labels: Feature

#151 [BUG] 내 클럽 리스트 클릭시 두번 불리는 버그, 내가 클럽 맴버에 포함되지 않는 버그 수정
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/Page/TabBarController.swift
  IDo/Util/FBURLCache.swift
  IDo/Util/MyProfile.swift
Labels: BUG

#152 [FEAT]: 마이프로필 카테고리 피커뷰 추가
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
Labels: Feature

#154 [FIX] : 🐛 storage에 이미지가 없을 때와 있을 때로 구별해서 앱이 종료되는 현상 수정
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
Labels: Refactor

#155 [FIX] : 🐛 이미지 전체가 아니라 누락되는 버그 수정
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
Labels: Refactor

#158 [BUG] 프로필 이미지가 없을때 로그인이랑 회원가입이 안되는버그 수정
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Util/MyProfile.swift
Labels: BUG

#160 [FEAT] 마이프로필에 내 작성글 리스트 제외시킴
  IDo.xcodeproj/project.pbxproj
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
Labels: UI

#161 [DESIGN] : 🎨 네비게이션 통일(뒤로가기 글씨 삭제 및 폰트 통일…
  IDo.xcodeproj/project.pbxproj
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/Util/NavigationBar.swift
Labels: Refactor, UI

#162 [FEAT] 다크모드 제외, 클럽 이미지 불러오기전에 클럽 클릭시 이미지를 못 불러오는 버그 수정
  IDo/Info.plist
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
Labels: BUG

#163 [DESIGN] : 🎨 인디케이터 가로 넓이 수정
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: UI

#164 [FEAT] LightMode만 가능하도록 변경
  IDo.xcodeproj/project.pbxproj
  IDo/GoogleService-Info.plist
  IDo/Info.plist
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG

#165 [FEAT] 개인정보 처리방침, 이용약관 하이버링크로 연결
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature, UI

#166 [FIX] 키보드 엔터키 입력시 키보드가 닫히도록 구현 + 회원가입 비밀번호 입력시 뷰가 올라가는 부분 일단 제외
  IDo/Page/LoginPage/LoginViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, UI

#167 [DESIGN]: SE버전 카테고리 가운데로 조정
  IDo.xcodeproj/project.pbxproj
  IDo/Page/CategoryPage/Cell/CategoryCollectionCell.swift
Labels: UI

#168 [FEAT] 회원가입시 자기소개 내용 DB에 저장기능 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Base.lproj/LaunchScreen.storyboard
  IDo/Info.plist
  IDo/Model/FBDatabaseManager.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: Feature

#169 [FEAT]: CategoryViewController 코드 정리 및 레이아웃 설정
  IDo/Page/CategoryPage/CategoryViewController.swift
Labels: Feature, UI

#172 [FIX] : 🔧 프로필 생성 화면 textField -> textView
  IDo/Base.lproj/LaunchScreen.storyboard
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/HomeEmptyView.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/SceneDelegate.swift
Labels: Refactor, UI

#173 [FIX]: 모임생성 이미지 설정 및 레이아웃 조정
  IDo/Page/NoticeBoard/NoticeHomeController.swift
Labels: BUG, UI

#174 [Fix] 홈 화면에서 자기가 만든 모임은 이동안돼는 버그 + 모임 삭제시 홈 화면에서는 보이는 버그 + 홈 화면에서 자기가 만든 모임 삭제시 모임이 남아있는 버그 수정
  IDo.xcodeproj/project.pbxproj
  IDo/Model/MeetingsData.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Util/MyProfile.swift
Labels: BUG

#177 [FIX]: 이메일을 인증하고 이메일을 바꿔도 인증 완료인 상태 대응
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, Feature

#178 [FIX] : 🐛 게시글 생성 시, 이미지 삭제로 인한 앱 다운
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
Labels: Refactor

#179 [FIX] : 🔧 게시판 생성 화면 스크롤 뷰 추가
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/SceneDelegate.swift
Labels: Refactor

#181 [FIX] : 🐛 게시판 이미지 관련 버그(Storage와 연동 관련 문제)
  IDo.xcodeproj/project.pbxproj
  IDo/Model/NoticeBoard.swift
  IDo/Model/NoticeBoardImagePath.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/SceneDelegate.swift
  IDo/Util/FBURLCache.swift
Labels: Refactor

#182 [FEAT] 회원가입 프로필 설정 화면, 마이프로필, 모임생성, 모임 수정, 게시판 생성 화면 키보드 대응 + 마이프로필 수정중 취소 기능
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardView.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
Labels: Feature, UI

#183 [FIX]: 모임 생성하기 버튼을 두번 누를 수 없게 구현
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
Labels: BUG, Feature

#184 [FIX] : 🐛 게시글 상세 더보기 버튼 규격 조정 / 게시글 삭제 시, 바로 목록으로 화면 이동 / 게시글 삭제 시, Storage에서 이미지 삭제 동기화
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
  IDo/SceneDelegate.swift
Labels: Refactor

#185 [FIX] 프로필 수정 취소시 텍스트 카운트가 변하지 않는 버그, 취소버튼 클릭시 취소버튼이 사라지지 않는 버그 수정
  IDo.xcodeproj/project.pbxproj
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: UI

#186 [FIX]: 가입하기,모임 수정하기, 모임생성 버튼 두번 클릭 막음.
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
  IDo/SceneDelegate.swift
Labels: BUG, Refactor, Feature

#187 [FIX] : 🐛 게시글 수정 시, 바로 게시글 상세 페이지에 적용
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
Labels: Refactor

#188 [FIX]: 게시글 작성 완료, 및 댓글 작성 2번 클릭 시 2개 작성되는 부분 수정
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/CommentStackView.swift
  IDo/Page/SignUpPage/CategorySelectViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/Page/SignUpPage/SignUpViewController.swift
Labels: BUG, Feature

#191 [FIX] 모임 업데이트 시 모임 화면에서 바로 적용 / 홈 화면에서 바로 적용
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
Labels: Refactor

#192 [FIX]: 모임 가입하기 두번 클릭 비활성화
  IDo/Page/NoticeBoard/NoticeHomeController.swift
Labels: BUG, Feature

#194 [Fix] 게시판 이미지 셀을 못가져오는 버그 수정
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
Labels: BUG, UI

#195 [FIX] 이미지를 잘못 가져오는 버그 수정 + 모임 리스트에 모임이 많을 경우 버벅이는 문제 해결
  IDo.xcodeproj/project.pbxproj
  IDo/Enum/ImageSize.swift
  IDo/Model/MeetingsData.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/Util/FBURLCache.swift
  IDo/View/BasicCell.swift
Labels: BUG

#196 [FIX] 홈화면에서 이미지를 못가져오는 버그 수정
  IDo/Model/MeetingsData.swift
  IDo/SceneDelegate.swift
Labels: BUG, UI

#198 [FIX] 모임을 생성할때 이미지가 겹쳐서 나오거나 다른 이미지가 나오는 버그 수정 + 모임 삭제시 내 모임 목록이 전부 안보이는 버그 해결
  IDo/Page/CategoryPage/MeetingViewController.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Util/FBURLCache.swift
  IDo/View/BasicCell.swift
Labels: BUG

#199 [Fix] 클럽을 삭제해도 클럽이 화면에 남아있는 버그 수정
  IDo/Model/MeetingsData.swift
  IDo/Page/CategoryPage/MeetingViewController.swift
Labels: BUG

#202 [FIX] : 🐛 회원 탈퇴 시, 연관 데이터 삭제 버그 수정
  IDo/Model/FBDatabaseManager.swift
  IDo/Model/MyProfileUpdateManager.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/SceneDelegate.swift
  IDo/Util/MyProfile.swift
Labels: Refactor

#203 [FEAT] : ⚙️ 회원탈퇴 시, 비밀번호 입력을 통한 이중 보안(재인증)
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: Feature

#207 [FIX] : 🔧 프로필을 선택하지 않은 사용자의 프로필 처리
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/CommentStackView.swift
  IDo/Page/NoticeBoardDetailPage/View/WriterStackView.swift
Labels: Refactor, UI

#208 [FEAT] : ⚙️ 마이프로필에서 닉네임 제한, 닉네임이 없을 시 알림창 생성
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/CategoryPage/Cell/CategoryCollectionCell.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/CreateNoticeBoard/CreateNoticeBoardViewController.swift
  IDo/Page/SignUpPage/SignUpProfileViewController.swift
  IDo/SceneDelegate.swift
Labels: Refactor, Feature

#209 [FIX] : 🔧 프로필 편집 시, 타이틀 변경
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: UI

#210 [FEAT] : ⚙️ 모임 멤버 목록에 방장 표시 추가
  IDo/Page/CategoryPage/CategoryViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
Labels: Feature, UI

#211 [DESIGN] : 🎨 마이프로필 구분선 수정
  IDo/Page/MyProfilePage/MyProfileViewController.swift
Labels: UI

#212 [FEAT] : ⚙️ 프로필 이미지 클릭 시, 해당 유저 정보를 띄우기 & Usersummary에 hobbyList 추가
  IDo/Model/IDoUser.swift
  IDo/Model/MyUserInfo.swift
  IDo/Model/UserSummary.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoardDetailPage/Cell/CommentTableViewCell.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Page/NoticeBoardDetailPage/View/NoticeBoardDetailView.swift
  IDo/SceneDelegate.swift
Labels: Refactor, Feature

#213 [REFACTOR] : ♻️ 유저 프로필 클릭 시, 유저 정보 보여주는 기능 모듈화
  IDo.xcodeproj/project.pbxproj
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Util/PresentToProfileVC.swift
Labels: Refactor

#215 [FIX] 댓글 카운트 증가하지 않는 버그 수정 + 게시판 상세화면 댓글 CRUD 조금 리펙토링
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: BUG, Refactor

#216 [FEAT] 댓글 추가, 수정, 삭제시에도 클럽이 존재하지 않거나 추방당한 경우 경고 메세지후 나가지도록 기능 구현
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
Labels: Feature

#217 [FIX] xcode 디버깅 경고 제거, 다크모드 미지원, 자동 로그인기능
  IDo.xcodeproj/project.pbxproj
  IDo/IDo.entitlements
  IDo/Info.plist
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/SceneDelegate.swift
Labels: BUG

#218 [FIX] 17버전에서 이미지 선택 버튼 클릭시 앱이 종료되는 버그 해결
  IDo/Page/MeetingPage/MeetingCreateViewController.swift
  IDo/Page/MeetingPage/MeetingManageViewController.swift
Labels: BUG

#219 [FIX] 클럽이 삭제 될경우 사용자들의 myClubList에서 제거 안되는 버그 수정
  IDo/Model/MyProfileUpdateManager.swift
  IDo/Page/HomePage/HomeViewController.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeHomeController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/SceneDelegate.swift
  IDo/Util/MyProfile.swift
Labels: BUG

#220 [FEAT] 유저 차단 기능 추가
  IDo.xcodeproj/project.pbxproj
  IDo/Model/IDoUser.swift
  IDo/Model/MeetingsData.swift
  IDo/Model/MyProfileUpdateManager.swift
  IDo/Model/MyUserInfo.swift
  IDo/Page/MyProfilePage/BlockListViewController.swift
  IDo/Page/MyProfilePage/MyProfileViewController.swift
  IDo/Page/NoticeBoard/Cell/MemberTableViewCell.swift
  IDo/Page/NoticeBoard/Cell/NoticeBoardTableViewCell.swift
  IDo/Page/NoticeBoard/FirebaseClubDatabaseManager.swift
  IDo/Page/NoticeBoard/NoticeBoardCRUD.swift
  IDo/Page/NoticeBoard/NoticeBoardViewController.swift
  IDo/Page/NoticeBoard/NoticeMeetingController.swift
  IDo/Page/NoticeBoardDetailPage/FirebaseCommentManager.swift
  IDo/Page/NoticeBoardDetailPage/NoticeBoardDetailViewController.swift
  IDo/Util/MyProfile.swift
  IDo/View/AlertManager.swift
  IDo/View/EmptyMessageStackView.swift
Labels: Feature

#223 [PACK] : 🎁파이어베이스 테스트용 배포용 분리
  IDo.xcodeproj/project.pbxproj
  IDo/AppDelegate.swift
  IDo/FirebaseInfo/Release/GoogleService-Info-Release.plist
Labels: Feature
